desafio-back-votos-api:
  user-info-api-url: https://user-info.herokuapp.com
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: desafio-back-votos-api
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    locations: classpath:db/migration
    schemas: desafio_back_votos_api
    table: flyway_schema_history
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: desafio_back_votos_api
---
feign:
  client:
    config:
      default:
        loggerLevel: full
---
logging:
  level:
    root: info
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
