desafio-back-votos-api:
  user-info-api-url: https://user-info.herokuapp.com
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: desafio-back-votos-api
  mvc:
    locale: pt_BR
    locale-resolver: fixed
  datasource:
    url: jdbc:postgresql://ec2-54-158-232-223.compute-1.amazonaws.com:5432/dbth82u78hmf4b
    username: eubhszzjkbfzlk
    password: 2093753ff4d1c1f20286dbd22f1f65b9a378a55552b3647d0b86a8b18a38570d
  flyway:
    enabled: true
    url: jdbc:postgresql://ec2-54-158-232-223.compute-1.amazonaws.com:5432/dbth82u78hmf4b
    username: eubhszzjkbfzlk
    password: 2093753ff4d1c1f20286dbd22f1f65b9a378a55552b3647d0b86a8b18a38570d
    locations: classpath:db/migration
    schemas: desafio_back_votos_api
    table: flyway_schema_history
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: desafio_back_votos_api
---
feign:
  client:
    config:
      default:
        loggerLevel: full
---
logging:
  level:
    root: info
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
