-------------------------------------------------------------------------
----------------- DESAFIO_BACK_VOTOS_API.ASSOCIADO ----------------------
-------------------------------------------------------------------------


-- CREATE SEQUENCE --
CREATE SEQUENCE DESAFIO_BACK_VOTOS_API.ASSOCIADO_SEQ INCREMENT BY 1 MINVALUE 1 START WITH 1;

-- CREATE TABLE --
CREATE TABLE DESAFIO_BACK_VOTOS_API.ASSOCIADO
(
    ID_ASSOCIADO BIGINT DEFAULT nextval('DESAFIO_BACK_VOTOS_API.ASSOCIADO_SEQ') PRIMARY KEY NOT NULL,
    CPF VARCHAR(11) NOT NULL
);

-- COMMENTS --
COMMENT ON TABLE  DESAFIO_BACK_VOTOS_API.ASSOCIADO IS 'Tabela responsável por armarzenar os dados cadastrais dos associados.';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.ASSOCIADO.ID_ASSOCIADO IS 'ID sequencial da tabela. Sequence: DESAFIO_BACK_VOTOS_API.ASSOCIADO_SEQ';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.ASSOCIADO.CPF IS 'CPF do associado.';

-- GRANTS --
GRANT SELECT, UPDATE ON SEQUENCE DESAFIO_BACK_VOTOS_API.ASSOCIADO_SEQ TO EUBHSZZJKBFZLK;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE DESAFIO_BACK_VOTOS_API.ASSOCIADO TO EUBHSZZJKBFZLK;

