-------------------------------------------------------------------------
----------------- DESAFIO_BACK_VOTOS_API.VOTO -------------------------
-------------------------------------------------------------------------


-- CREATE SEQUENCE --
CREATE SEQUENCE DESAFIO_BACK_VOTOS_API.VOTO_SEQ INCREMENT BY 1 MINVALUE 1 START WITH 1;

-- CREATE TABLE --
CREATE TABLE DESAFIO_BACK_VOTOS_API.VOTO
(
    ID_VOTO BIGINT DEFAULT nextval('DESAFIO_BACK_VOTOS_API.VOTO_SEQ') PRIMARY KEY NOT NULL,
    VOTO VARCHAR(3) NOT NULL,
    ID_ASSOCIADO BIGINT NOT NULL,
    ID_SESSAO BIGINT NOT NULL,
    CONSTRAINT FK_VOTO_ASSOCIADO FOREIGN KEY (ID_ASSOCIADO) REFERENCES DESAFIO_BACK_VOTOS_API.ASSOCIADO(ID_ASSOCIADO),
    CONSTRAINT FK_VOTO_SESSAO FOREIGN KEY (ID_SESSAO) REFERENCES DESAFIO_BACK_VOTOS_API.SESSAO(ID_SESSAO)
);

-- COMMENTS --
COMMENT ON TABLE  DESAFIO_BACK_VOTOS_API.VOTO IS 'Tabela responsável por armarzenar os votos.';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.VOTO.ID_VOTO IS 'ID sequencial da tabela. Sequence: DESAFIO_BACK_VOTOS_API.VOTO_SEQ';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.VOTO.VOTO IS 'Voto do associado.';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.VOTO.ID_ASSOCIADO IS 'Id do associado.';
COMMENT ON COLUMN DESAFIO_BACK_VOTOS_API.VOTO.ID_SESSAO IS 'Id da sessão.';

-- GRANTS --
GRANT SELECT, UPDATE ON SEQUENCE DESAFIO_BACK_VOTOS_API.VOTO_SEQ TO EUBHSZZJKBFZLK;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE DESAFIO_BACK_VOTOS_API.VOTO TO EUBHSZZJKBFZLK;

